# test/dummy/Gemfile
source "https://rubygems.org"

gem "rails", "~> 8.0"
gem "sqlite3", "2.9.5"
gem "pg"

# Load environment variables from .env file
gem "dotenv-rails", groups: [ :development, :test ]

# Load the local Rails Pulse gem
gem "rails_pulse", path: "../.."

gem "puma", "7.2.1"
gem "css-zero", "1.1.5"

group :development, :test do
  gem "pry-byebug"
  gem "debug"
end
