# test/dummy/Gemfile
source "https://rubygems.org"

gem "rails", "8.0.1"
gem "sqlite3", "2.6.0"
gem "pg"

# Load environment variables from .env file
gem "dotenv-rails", groups: [ :development, :test ]

# Load the local Rails Pulse gem
gem "rails_pulse", path: "../.."

gem "puma", "6.6.0"
gem "lucide-rails", "0.5.1"
gem "css-zero", "1.1.5"
gem "groupdate"

group :development, :test do
  gem "pry-byebug"
  gem "debug"
  gem "benchmark-ips"
  gem "memory_profiler"
end
