# test/dummy/Gemfile
source "https://rubygems.org"

gem "rails", "8.0.1"
gem "sqlite3", "2.6.0"

# Load the local Rails Pulse gem
gem "rails_pulse", path: "../.."

# Add other dependencies as needed (e.g., puma, lucide-rails)
gem "puma", "6.6.0"
gem "lucide-rails", "0.5.1"
gem "rails_charts", "0.0.6"
gem "css-zero", "1.1.5"
