# Monkey patch for RailsCharts CSP compliance
# This adds nonce attributes to script tags generated by the RailsCharts gem

if defined?(RailsCharts)
  module RailsCharts
    module CspPatch
      def line_chart(data_source, options = {})
        # Get the original chart HTML
        chart_html = super(data_source, options)

        # Try to get CSP nonce from various sources
        nonce = get_csp_nonce

        if nonce.present? && chart_html.present?
          # Add nonce to all script tags in the chart HTML
          chart_html = add_nonce_to_scripts(chart_html.to_s, nonce)
          # Ensure the HTML is marked as safe for Rails to render
          chart_html = chart_html.html_safe if chart_html.respond_to?(:html_safe)
        end

        chart_html
      end

      private

      def get_csp_nonce
        # Try various methods to get the CSP nonce
        nonce = nil

        # Method 1: Check for Rails 6+ CSP nonce helper
        if respond_to?(:content_security_policy_nonce)
          nonce = content_security_policy_nonce
        end

        # Method 2: Check for custom csp_nonce helper
        if nonce.blank? && respond_to?(:csp_nonce)
          nonce = csp_nonce
        end

        # Method 3: Check request environment
        if nonce.blank? && defined?(request) && request
          nonce = request.env["action_dispatch.content_security_policy_nonce"] ||
                  request.env["secure_headers.content_security_policy_nonce"] ||
                  request.env["csp_nonce"]
        end

        # Method 4: Check thread/request store
        if nonce.blank?
          nonce = Thread.current[:rails_pulse_csp_nonce] ||
                  (defined?(RequestStore) && RequestStore.store[:rails_pulse_csp_nonce])
        end

        nonce.presence
      end

      def add_nonce_to_scripts(html, nonce)
        # Use regex to add nonce to script tags that don't already have one
        html.gsub(/<script(?![^>]*\snonce=)([^>]*)>/i) do |match|
          # Insert nonce attribute before the closing >
          attributes = $1
          if attributes.strip.empty?
            "<script nonce=\"#{nonce}\">"
          else
            "<script#{attributes} nonce=\"#{nonce}\">"
          end
        end
      end
    end
  end
end

# Apply the patch to ApplicationHelper and any modules that include chart helpers
Rails.application.config.to_prepare do
  if defined?(RailsCharts)
    # Patch ActionView::Base to include our CSP patch for line_chart
    ActionView::Base.prepend(RailsCharts::CspPatch)

    # Also patch any Rails Pulse helpers that might use charts
    if defined?(RailsPulse::ApplicationHelper)
      RailsPulse::ApplicationHelper.prepend(RailsCharts::CspPatch)
    end
  end
end
