# CSP patch for RailsCharts gem
# Adds nonce attributes to script tags generated by RailsCharts for CSP compliance

if defined?(RailsCharts)
  module RailsCharts
    module CspPatch
      def line_chart(data_source, options = {})
        chart_html = super(data_source, options)
        add_csp_nonce_to_chart(chart_html)
      end

      def bar_chart(data_source, options = {})
        chart_html = super(data_source, options)
        add_csp_nonce_to_chart(chart_html)
      end

      private

      def add_csp_nonce_to_chart(chart_html)
        return chart_html unless chart_html.present?

        nonce = get_csp_nonce
        return chart_html unless nonce.present?

        # Add nonce to script tags and mark as safe
        modified_html = add_nonce_to_scripts(chart_html.to_s, nonce)
        modified_html.html_safe if modified_html.respond_to?(:html_safe)
      end

      def get_csp_nonce
        # Try common CSP nonce sources in order of preference
        if respond_to?(:content_security_policy_nonce)
          content_security_policy_nonce
        elsif respond_to?(:csp_nonce)
          csp_nonce
        elsif defined?(request) && request
          request.env["action_dispatch.content_security_policy_nonce"] ||
          request.env["secure_headers.content_security_policy_nonce"] ||
          request.env["csp_nonce"]
        elsif respond_to?(:controller) && controller.respond_to?(:content_security_policy_nonce)
          controller.content_security_policy_nonce
        elsif defined?(@view_context) && @view_context.respond_to?(:content_security_policy_nonce)
          @view_context.content_security_policy_nonce
        else
          Thread.current[:rails_pulse_csp_nonce] ||
          (defined?(RequestStore) && RequestStore.store[:rails_pulse_csp_nonce])
        end
      end

      def add_nonce_to_scripts(html, nonce)
        html.gsub(/<script(?![^>]*\snonce=)([^>]*)>/i) do |match|
          attributes = $1
          if attributes.strip.empty?
            "<script nonce=\"#{nonce}\">"
          else
            "<script#{attributes} nonce=\"#{nonce}\">"
          end
        end
      end
    end
  end
end

# Apply the CSP patch only to Rails Pulse helpers, not the entire application
# By prepending to ChartHelper instead of ApplicationHelper, we scope the patch to RailsPulse
# namespace only, avoiding conflicts with any chart libraries in the host application
# (Chartkick, Highcharts, Google Charts, ApexCharts, custom helpers, etc.)
Rails.application.config.to_prepare do
  if defined?(RailsCharts) && defined?(RailsPulse::ChartHelper)
    # Prepend CSP patch to RailsPulse::ChartHelper
    # This wraps only the rails_charts methods, ensuring clean CSP nonce injection
    # without affecting the host application's chart helpers
    RailsPulse::ChartHelper.prepend(RailsCharts::CspPatch)
  end
end
