# Generated by rails_pulse:install_cloud - loads the Rails Pulse Cloud schema definition
class InstallRailsPulseCloudTables < ActiveRecord::Migration[<%= Rails::VERSION::MAJOR %>.<%= Rails::VERSION::MINOR %>]
  def up
    if rails_pulse_cloud_installed?
      say "Rails Pulse Cloud tables already exist. Skipping installation.", :yellow
      return
    end

    # Load and execute the Cloud schema directly, so this migration always
    # creates the tables as db/rails_pulse_cloud_schema.rb describes them.
    schema_file = File.join(::Rails.root.to_s, "db/rails_pulse_cloud_schema.rb")
    raise "Rails Pulse Cloud schema file not found at db/rails_pulse_cloud_schema.rb" unless File.exist?(schema_file)

    say "Loading Rails Pulse Cloud schema from db/rails_pulse_cloud_schema.rb"
    load schema_file
    RailsPulse::CloudSchema.call(connection)
    say "Rails Pulse Cloud tables created successfully"
  end

  def down
    drop_table :rails_pulse_cloud_batches if table_exists?(:rails_pulse_cloud_batches)
    drop_table :rails_pulse_cloud_installations if table_exists?(:rails_pulse_cloud_installations)
  end

  private

  def rails_pulse_cloud_installed?
    table_exists?(:rails_pulse_cloud_installations) && table_exists?(:rails_pulse_cloud_batches)
  end
end
